export const DATA_WEATHER_REQUEST = 'DATA_WEATHER_REQUEST';
export const DATA_WEATHER_RESPONSE = 'DATA_WEATHER_RESPONSE';
export const DATA_WEATHER_FAILED = 'DATA_WEATHER_FAILED';

export const DATA_FORECAST_REQUEST = 'DATA_FORECAST_REQUEST';
export const DATA_FORECAST_RESPONSE = 'DATA_FORECAST_RESPONSE';
export const DATA_FORECAST_FAILED = 'DATA_FORECAST_FAILED';

export const FETCH_COORDS = 'FETCH_COORDS';
